export { default as Icon10TitlebarClose } from './Icon10TitlebarClose.svg'
export { default as Icon10TitlebarMaximize } from './Icon10TitlebarMaximize.svg'
export { default as Icon12TitlebarMinimize } from './Icon12TitlebarMinimize.svg'
export { default as Icon12TitlebarRestore } from './Icon12TitlebarRestore.svg'
export { default as Icon16Spinner } from './Icon16Spinner.svg'
export { default as Icon24Spinner } from './Icon24Spinner.svg'
export { default as Icon32Spinner } from './Icon32Spinner.svg'
export { default as Icon44Spinner } from './Icon44Spinner.svg'
