name: Build VK Desktop

on:
  release:
    types: [published]

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            files: '"app/VK Desktop linux x64.zip" "app/VK Desktop linux ia32.zip"'
          - os: windows-latest
            files: '"app/VK Desktop Setup x64.exe" "app/VK Desktop Setup x32.exe"'
          - os: macos-latest
            files: '"app/VK Desktop mac x64.dmg" "app/VK Desktop mac arm64.dmg"'

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: yarn
    - name: Build Electron app
      run: yarn build
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Create installer
      if: startsWith(matrix.os, 'windows')
      run: yarn win-setup
    - name: Upload binaries to release
      run: gh release upload ${{ github.event.release.tag_name }} ${{ matrix.files }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
