name: run lint, tsc and build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn
      - name: Try lint
        run: yarn lint
      - name: Try build code (with tsc)
      - run: yarn dist
